version: "3.7"

services:
  app:
    build:
      context: .
    container_name: app
    working_dir: /app
    command: cargo watch -x run
    tty: true
    volumes:
      - ./:/app
    ports:
      - 3000:3000
